### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2753756325 at line 1 column 159 path $.DataSet[0].BackupSize

### ISSUE THREAD

**Issue by midaug** [ucloud/ucloud-sdk-java#4]
describeUDBBackup 查询异常

测试代码：
        Account account = new Account(publicKey, privateKey);
        UDBClient client = new DefaultUDBClient(new UDBConfig(account));
        DescribeUDBBackupParam param = new DescribeUDBBackupParam("cn-sh2", 10, 0);
        try {
            Long s = System.currentTimeMillis();
            System.out.println(JSON.toJSONString(client.describeUDBBackup(param)));
            System.out.println(System.currentTimeMillis() - s);
        } catch (Exception e) {
            e.printStackTrace();
        }

异常信息：
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2753756325 at line 1 column 159 path $.DataSet[0].BackupSize
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at cn.ucloud.common.http.Http.doHttp(Http.java:49)
	at cn.ucloud.common.http.UcloudHttpImpl.doGet(UcloudHttpImpl.java:41)
	at cn.ucloud.udb.client.DefaultUDBClient.describeUDBBackup(DefaultUDBClient.java:422)
	at ecarx.wf.ucloud.UcloudTest.main(UcloudTest.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NumberFormatException: Expected an int but was 2753756325 at line 1 column 159 path $.DataSet[0].BackupSize
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
	... 21 more

**Comment by peggypig** [comment]
这个异常是由于BackupSize=2753756325超过了Integer的最大值造成的，这个问题会在下个版本修复，感谢反馈

**Comment by midaug** [comment]
> 这个异常是由于BackupSize=2753756325超过了Integer的最大值造成的，这个问题会在下个版本修复，感谢反馈

请问下个版本大概是什么时候发布呢？

**Comment by peggypig** [comment]
@midaug SDK已经更新，最新版本为0.8.2.6-release，中央仓库大约在下午1点左右会生效

**Comment by midaug** [comment]
已经成功获取到SDK，并测试成功了
