### ISSUE TITLE
USMS-SDK发送短信校验Exception

### ISSUE THREAD

**Issue by rainandsunshine** [ucloud/ucloud-sdk-java#7]
- cn.ucloud.common.pojo.BaseRequestParam
- cn.ucloud.usms.model.SendUSMSMessageParam
这两个参数引入了 `javax.validation.constraints.NotEmpty`，导致最后参数校验时找不到注解，第三方引入会抛出异常。
异常如下：
~~~java

javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotEmpty' validating type 'java.lang.String'. Check configuration for 'templateId'

	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.throwExceptionForNullValidator(ConstraintTree.java:229)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getConstraintValidatorNoUnwrapping(ConstraintTree.java:310)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getConstraintValidatorInstanceForAutomaticUnwrapping(ConstraintTree.java:244)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getInitializedConstraintValidator(ConstraintTree.java:163)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:116)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:87)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:73)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:621)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:584)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:528)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:496)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:461)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:411)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:208)
	at cn.ucloud.common.util.ParamValidator.validator(ParamValidator.java:25)
	at cn.ucloud.common.util.ParamConstructor.getHttpPostParamString(ParamConstructor.java:73)
	at cn.ucloud.common.http.UcloudHttpImpl.doPost(UcloudHttpImpl.java:56)
	at cn.ucloud.usms.client.DefaultUSMSClient.sendUSMSMessage(DefaultUSMSClient.java:24)
~~~
需要换成`org.hibernate.validator.constraints.NotEmpty` 可正常运行

**Comment by fioncat** [comment]
Hello，抱歉回复晚了。这个问题在最新版本已经修复了，请将sdk版本更新至1.0.x-release
